# Generated by Django 4.1.7 on 2023-11-04 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quota',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.zone'),
        ),
        migrations.AddField(
            model_name='promoter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promoter',
            name='zone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.zone'),
        ),
        migrations.AddIndex(
            model_name='level',
            index=models.Index(fields=['code'], name='employee_le_code_5db4ec_idx'),
        ),
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.level'),
        ),
        migrations.AddField(
            model_name='employee',
            name='type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.typedocument'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ubigeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utils.ubigeo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['code'], name='employee_zo_code_54726b_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisor',
            index=models.Index(fields=['code'], name='employee_su_code_2f2e80_idx'),
        ),
        migrations.AddIndex(
            model_name='quota',
            index=models.Index(fields=['anio'], name='employee_qu_anio_566bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='quota',
            index=models.Index(fields=['mes'], name='employee_qu_mes_c57efe_idx'),
        ),
        migrations.AddIndex(
            model_name='quota',
            index=models.Index(fields=['periodo'], name='employee_qu_periodo_dae60b_idx'),
        ),
        migrations.AddIndex(
            model_name='promoter',
            index=models.Index(fields=['code'], name='employee_pr_code_6ecbfa_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user'], name='employee_em_user_id_6aa707_idx'),
        ),
    ]
