# Generated by Django 4.1.7 on 2023-11-04 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('clients', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Codigo')),
                ('nro_document', models.CharField(max_length=20, verbose_name='Documento')),
                ('company_name', models.CharField(max_length=255, verbose_name='Razon_social')),
                ('fiscal_address', models.CharField(max_length=255, verbose_name='Domicilio_Fiscal')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Distribuitor',
                'verbose_name_plural': 'Distribuitors',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductDistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, verbose_name='Codigo')),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'ProductDistributor',
                'verbose_name_plural': 'ProductsDistributors',
                'ordering': ['distributor', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code_client', models.CharField(max_length=20, verbose_name='Codigo_cliente')),
                ('company_name', models.CharField(max_length=255, verbose_name='Razon_social')),
                ('commercial_name', models.CharField(max_length=255, verbose_name='Nombre_comercial')),
                ('district', models.CharField(max_length=50, verbose_name='Distrito')),
                ('code_product', models.CharField(max_length=10, verbose_name='Codigo_producto')),
                ('code_product_distributor_first', models.CharField(max_length=20, verbose_name='Codigo_producto_distribuidora_primero')),
                ('code_product_distributor_second', models.CharField(max_length=20, null=True, verbose_name='Codigo_producto_distribuidora_segundo')),
                ('description_product', models.CharField(max_length=255, verbose_name='Descripcion_producto')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('value', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Valor')),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Precio')),
                ('code_promoter', models.CharField(max_length=10, verbose_name='Codigo_promotor')),
                ('name_promoter', models.CharField(max_length=255, verbose_name='Nombre_promotor')),
                ('code_vendedor', models.CharField(max_length=10, verbose_name='Codigo_vendedor')),
                ('serie_invoice', models.CharField(max_length=4, verbose_name='Serie_comprobante')),
                ('nro_invoice', models.CharField(max_length=8, verbose_name='Nro_comprobante')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='distributors.distributor')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utils.period')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['distributor', 'client'],
            },
        ),
    ]
