# Generated by Django 4.1.7 on 2023-11-04 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('clients', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesclient',
            name='promoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.promoter'),
        ),
        migrations.AddField(
            model_name='sitesclient',
            name='ubigeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utils.ubigeo'),
        ),
        migrations.AddField(
            model_name='contact',
            name='sites_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.sitesclient'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.typeclient'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utils.typedocument'),
        ),
        migrations.AddField(
            model_name='client',
            name='ubigeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utils.ubigeo'),
        ),
        migrations.AddIndex(
            model_name='sitesclient',
            index=models.Index(fields=['code'], name='clients_sit_code_e253b1_idx'),
        ),
        migrations.AddIndex(
            model_name='sitesclient',
            index=models.Index(fields=['commercial_name'], name='clients_sit_commerc_7e2474_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['item'], name='clients_con_item_dc222e_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['name'], name='clients_con_name_416cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['code'], name='clients_cli_code_d90b4a_idx'),
        ),
    ]
